
import React from 'react';
import { Recipe } from '../types';

interface RecipeCardProps {
  recipe: Recipe;
  isLiked: boolean;
  onLike: (recipe: Recipe) => void;
  onShare: (recipe: Recipe) => void;
}

const RecipeCard: React.FC<RecipeCardProps> = ({ recipe, isLiked, onLike, onShare }) => {
  const downloadRecipe = () => {
    const content = `
${recipe.title.toUpperCase()}
Category: ${recipe.category}
---
Description: ${recipe.description}
Prep Time: ${recipe.prepTime} | Cook Time: ${recipe.cookTime}
Servings: ${recipe.servings}
Calories: ${recipe.nutrition.calories}

INGREDIENTS:
${recipe.ingredients.map(i => `- ${i}`).join('\n')}

INSTRUCTIONS:
${recipe.instructions.map((step, i) => `${i + 1}. ${step}`).join('\n')}

Generated by QuickBite AI
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${recipe.title.toLowerCase().replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white rounded-[2rem] shadow-sm overflow-hidden border border-slate-100 flex flex-col mb-4">
      {/* Image Section */}
      <div className="relative h-60 overflow-hidden">
        <img 
          src={recipe.imageUrl} 
          alt={recipe.title} 
          className="w-full h-full object-cover"
        />
        <div className="absolute top-4 left-4">
          <span className="bg-white/95 backdrop-blur shadow-sm text-orange-600 px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest">
            {recipe.category}
          </span>
        </div>
        <div className="absolute bottom-4 right-4 flex gap-2">
          <button 
            onClick={downloadRecipe}
            className="w-10 h-10 bg-white/95 backdrop-blur rounded-full flex items-center justify-center text-slate-700 active:scale-90 transition-transform shadow-md"
            title="Download Recipe"
          >
            <i className="fa-solid fa-download text-sm"></i>
          </button>
          <button 
            onClick={() => onShare(recipe)}
            className="w-10 h-10 bg-white/95 backdrop-blur rounded-full flex items-center justify-center text-slate-700 active:scale-90 transition-transform shadow-md"
            title="Share Recipe"
          >
            <i className="fa-solid fa-arrow-up-from-bracket text-sm"></i>
          </button>
          <button 
            onClick={() => onLike(recipe)}
            className={`w-10 h-10 rounded-full flex items-center justify-center transition-all shadow-md active:scale-90 ${
              isLiked 
                ? 'bg-red-500 text-white' 
                : 'bg-white/95 text-slate-700'
            }`}
          >
            <i className={`fa-${isLiked ? 'solid' : 'regular'} fa-heart`}></i>
          </button>
        </div>
      </div>

      {/* Content Section */}
      <div className="p-6 space-y-6">
        <div>
          <h2 className="text-2xl font-serif font-black text-slate-900 leading-tight mb-2">
            {recipe.title}
          </h2>
          <p className="text-sm text-slate-500 italic line-clamp-2">"{recipe.description}"</p>
        </div>

        {/* Quick Stats */}
        <div className="flex justify-between items-center bg-slate-50 rounded-2xl p-4">
          <div className="text-center">
            <p className="text-[9px] uppercase font-black text-slate-400 mb-0.5">Time</p>
            <p className="text-xs font-bold text-slate-800">{recipe.cookTime}</p>
          </div>
          <div className="h-6 w-px bg-slate-200"></div>
          <div className="text-center">
            <p className="text-[9px] uppercase font-black text-slate-400 mb-0.5">Serves</p>
            <p className="text-xs font-bold text-slate-800">{recipe.servings}</p>
          </div>
          <div className="h-6 w-px bg-slate-200"></div>
          <div className="text-center">
            <p className="text-[9px] uppercase font-black text-slate-400 mb-0.5">Cal</p>
            <p className="text-xs font-bold text-slate-800">{recipe.nutrition.calories}</p>
          </div>
        </div>

        {/* Ingredients */}
        <div className="space-y-3">
          <h3 className="font-extrabold text-sm text-slate-900 flex items-center gap-2">
            <span className="w-1 h-4 bg-orange-500 rounded-full"></span>
            Ingredients
          </h3>
          <ul className="grid grid-cols-1 gap-2">
            {recipe.ingredients.slice(0, 6).map((ing, idx) => (
              <li key={idx} className="text-xs text-slate-600 flex items-center gap-3 bg-slate-50/50 p-2 rounded-lg">
                <div className="w-1.5 h-1.5 rounded-full bg-orange-300"></div>
                {ing}
              </li>
            ))}
            {recipe.ingredients.length > 6 && (
              <li className="text-[10px] text-slate-400 font-bold px-2 italic">
                + {recipe.ingredients.length - 6} more items
              </li>
            )}
          </ul>
        </div>

        {/* Instructions */}
        <div className="space-y-3">
          <h3 className="font-extrabold text-sm text-slate-900 flex items-center gap-2">
            <span className="w-1 h-4 bg-orange-500 rounded-full"></span>
            Instructions
          </h3>
          <div className="space-y-3">
            {recipe.instructions.map((step, idx) => (
              <div key={idx} className="flex gap-4">
                <span className="text-xs font-black text-orange-500 bg-orange-50 w-6 h-6 rounded-lg flex items-center justify-center flex-shrink-0">
                  {idx + 1}
                </span>
                <p className="text-xs text-slate-600 leading-relaxed">{step}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Nutrition Footer */}
        <div className="pt-4 border-t border-slate-100 flex justify-between">
          <span className="text-[10px] text-slate-400">P: <span className="text-slate-700 font-bold">{recipe.nutrition.protein}</span></span>
          <span className="text-[10px] text-slate-400">C: <span className="text-slate-700 font-bold">{recipe.nutrition.carbs}</span></span>
          <span className="text-[10px] text-slate-400">F: <span className="text-slate-700 font-bold">{recipe.nutrition.fat}</span></span>
        </div>
      </div>
    </div>
  );
};

export default RecipeCard;
